# ==============================================================================
# Service Installation
# ==============================================================================

# Ensure the oqto system user exists with a proper home directory.
# Called early in multi-user setup so EAVS/hstry/mmry config can be
# written into ~oqto/.config/ before services are installed.
# Safe to call multiple times (idempotent).
OQTO_HOME="/home/oqto"

ensure_octo_system_user() {
  if id oqto &>/dev/null; then
    OQTO_HOME=$(eval echo "~oqto")
    return 0
  fi

  log_info "Creating oqto system user with home at $OQTO_HOME..."
  # Use /bin/bash so admins can: sudo -su oqto
  # No password set, so direct/SSH login is impossible.
  sudo useradd -r -m -d "$OQTO_HOME" -s /bin/bash oqto

  # Create XDG directory structure
  sudo mkdir -p \
    "${OQTO_HOME}/.config" \
    "${OQTO_HOME}/.local/share" \
    "${OQTO_HOME}/.local/state"
  sudo chown -R oqto:oqto "$OQTO_HOME"

  # Create /var/lib/oqto for service data (referenced by systemd ReadWritePaths)
  sudo mkdir -p /var/lib/oqto/.local/share/oqto
  sudo chown -R oqto:oqto /var/lib/oqto

  log_success "Created oqto system user (home: $OQTO_HOME)"
}

install_service_linux() {
  log_step "Installing systemd service"

  if [[ "$SELECTED_USER_MODE" == "single" ]]; then
    # User-level services: runner + oqto backend
    local service_dir="$HOME/.config/systemd/user"
    mkdir -p "$service_dir"

    # Determine binary paths (system-wide install)
    local oqto_bin="/usr/local/bin/oqto"
    local oqto_runner_bin="/usr/local/bin/oqto-runner"

    # 1. hstry service (chat history)
    local hstry_bin="/usr/local/bin/hstry"
    [[ -x "$HOME/.local/bin/hstry" ]] && hstry_bin="$HOME/.local/bin/hstry"
    [[ -x "$HOME/.cargo/bin/hstry" ]] && hstry_bin="$HOME/.cargo/bin/hstry"

    local hstry_service="$service_dir/hstry.service"
    cat >"$hstry_service" <<EOF
[Unit]
Description=Oqto Chat History Service

[Service]
Type=simple
ExecStart=${hstry_bin} service run
Restart=always
RestartSec=3
Environment=PATH=%h/.bun/bin:%h/.cargo/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin
Environment=HOME=%h

[Install]
WantedBy=default.target
EOF
    log_success "hstry service file created: $hstry_service"

    # 2. mmry service (memory/embeddings)
    local mmry_bin="/usr/local/bin/mmry"
    [[ -x "$HOME/.local/bin/mmry" ]] && mmry_bin="$HOME/.local/bin/mmry"
    [[ -x "$HOME/.cargo/bin/mmry" ]] && mmry_bin="$HOME/.cargo/bin/mmry"

    local mmry_service="$service_dir/mmry.service"
    cat >"$mmry_service" <<EOF
[Unit]
Description=Oqto Memory Service

[Service]
Type=simple
ExecStart=${mmry_bin} service run
Restart=always
RestartSec=3
Environment=PATH=%h/.bun/bin:%h/.cargo/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin
Environment=HOME=%h

[Install]
WantedBy=default.target
EOF
    log_success "mmry service file created: $mmry_service"

    # 3. oqto-runner service (session management, hstry writes, process isolation)
    local runner_service="$service_dir/oqto-runner.service"
    cat >"$runner_service" <<EOF
# Oqto Runner - Process isolation daemon
# Generated by setup.sh
# The runner is the canonical path for all session management.

[Unit]
Description=Oqto Runner - Process isolation daemon
After=hstry.service mmry.service
Wants=hstry.service mmry.service

[Service]
Type=notify
ExecStart=${oqto_runner_bin} --socket %t/oqto-runner.sock
Restart=on-failure
RestartSec=5
TimeoutStartSec=30
Environment=RUST_LOG=info
Environment=PATH=%h/.bun/bin:%h/.cargo/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin
Environment=HOME=%h
Environment=PLAYWRIGHT_BROWSERS_PATH=${PW_BROWSERS_DIR:-$HOME/.local/share/playwright-browsers}

[Install]
WantedBy=default.target
EOF

    log_success "Runner service file created: $runner_service"

    # 2. oqto backend service (depends on runner)
    local service_file="$service_dir/oqto.service"
    cat >"$service_file" <<EOF
# Oqto Server - User service
# Generated by setup.sh

[Unit]
Description=Oqto Backend Server
After=oqto-runner.service
Wants=oqto-runner.service

[Service]
Type=simple
Environment=RUST_LOG=$OQTO_LOG_LEVEL
Environment=PATH=%h/.bun/bin:%h/.cargo/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin
Environment=HOME=%h
Environment=PLAYWRIGHT_BROWSERS_PATH=${PW_BROWSERS_DIR:-$HOME/.local/share/playwright-browsers}
EnvironmentFile=-$OQTO_CONFIG_DIR/env
ExecStart=${oqto_bin} serve --local-mode
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF

    log_success "Service file created: $service_file"

    # Export PLAYWRIGHT_BROWSERS_PATH in shell profile so all tools
    # (slidev, playwright CLI, agent browser, etc.) find the same browsers.
    local pw_path="${PW_BROWSERS_DIR:-$HOME/.local/share/playwright-browsers}"
    local pw_export="export PLAYWRIGHT_BROWSERS_PATH=\"$pw_path\""
    for rc_file in "$HOME/.zshrc" "$HOME/.bashrc"; do
      if [[ -f "$rc_file" ]] && ! grep -q 'PLAYWRIGHT_BROWSERS_PATH' "$rc_file"; then
        echo "" >> "$rc_file"
        echo "# Playwright browsers (shared by oqto, slidev, etc.)" >> "$rc_file"
        echo "$pw_export" >> "$rc_file"
        log_info "Added PLAYWRIGHT_BROWSERS_PATH to $(basename "$rc_file")"
      fi
    done

    # Enable linger so services start at boot without login
    if command_exists loginctl; then
      loginctl enable-linger "$(whoami)" 2>/dev/null || true
    fi

    if confirm "Enable and start services now?"; then
      systemctl --user daemon-reload
      systemctl --user enable hstry mmry oqto-runner oqto
      systemctl --user start hstry mmry
      sleep 2
      systemctl --user start oqto-runner
      sleep 2
      systemctl --user start oqto
      log_success "Services enabled and started"
      log_info "Check status with: systemctl --user status hstry mmry oqto-runner oqto"
      log_info "View logs with: journalctl --user -u oqto -f"
    else
      log_info "To enable manually:"
      log_info "  systemctl --user daemon-reload"
      log_info "  systemctl --user enable --now oqto-runner oqto"
    fi
  else
    # System-level service (requires sudo)
    log_info "Multi-user mode requires system-level service installation"

    if ! confirm "Install system service? (requires sudo)"; then
      log_info "Skipping service installation"
      return
    fi

    # Ensure oqto user exists (may already be created by ensure_octo_system_user)
    ensure_octo_system_user
    local octo_home="$OQTO_HOME"

    # Create runtime directories
    sudo mkdir -p /run/oqto
    sudo chown oqto:oqto /run/oqto

    # Runtime config in oqto's home (XDG layout: ~/.config/oqto/)
    # This is what the oqto service actually reads at startup.
    local octo_config_home="${octo_home}/.config/oqto"
    sudo mkdir -p "$octo_config_home"
    sudo cp "$OQTO_CONFIG_DIR/config.toml" "${octo_config_home}/config.toml"
    if [[ -f "$OQTO_CONFIG_DIR/env" ]]; then
      sudo cp "$OQTO_CONFIG_DIR/env" "${octo_config_home}/env"
      sudo chmod 600 "${octo_config_home}/env"
    fi

    # Also copy a baseline config to /etc/oqto/ for sandbox policy reference.
    # Sandbox configs (sandbox.toml, skdlr-agent.toml) live here too - these
    # are system-wide policy the admin controls, not per-service runtime config.
    sudo mkdir -p /etc/oqto
    sudo cp "$OQTO_CONFIG_DIR/config.toml" /etc/oqto/config.toml

    sudo chown -R oqto:oqto "$octo_home"

    # Install service file
    local service_file="/etc/systemd/system/oqto.service"

    sudo tee "$service_file" >/dev/null <<EOF
# Oqto Server - System service
# Generated by setup.sh

[Unit]
Description=Oqto Control Plane Server
After=network.target eavs.service oqto-usermgr.service
Wants=eavs.service oqto-usermgr.service

[Service]
Type=simple
User=oqto
Group=oqto
WorkingDirectory=${octo_home}
Environment=HOME=${octo_home}
Environment=XDG_CONFIG_HOME=${octo_home}/.config
Environment=XDG_DATA_HOME=${octo_home}/.local/share
Environment=XDG_STATE_HOME=${octo_home}/.local/state
Environment=OQTO_CONFIG=${octo_config_home}/config.toml
Environment=RUST_LOG=$OQTO_LOG_LEVEL
Environment=PLAYWRIGHT_BROWSERS_PATH=/usr/local/share/playwright-browsers
EnvironmentFile=-${octo_config_home}/env
ExecStart=/usr/local/bin/oqto serve
ExecStop=/bin/kill -TERM \$MAINPID
TimeoutStopSec=30
Restart=on-failure
RestartSec=5
ProtectSystem=strict
ReadWritePaths=${octo_home}
ReadWritePaths=/run/oqto
PrivateTmp=true
NoNewPrivileges=true
AmbientCapabilities=CAP_NET_BIND_SERVICE
EOF

    sudo tee -a "$service_file" >/dev/null <<EOF

[Install]
WantedBy=multi-user.target
EOF

    # Binaries are already in /usr/local/bin from build_octo

    log_success "Service file created: $service_file"

    # Install oqto-usermgr service (privileged user management daemon)
    install_usermgr_service

    # Install central mmry embeddings server (shared by all users)
    install_mmry_central_service

    # Ensure runner socket base directory exists at boot
    install_runner_socket_dirs

    if confirm "Enable and start the service now?"; then
      sudo systemctl daemon-reload
      sudo systemctl enable oqto
      sudo systemctl start oqto
      log_success "Service enabled and started"
      log_info "Check status with: sudo systemctl status oqto"
      log_info "View logs with: sudo journalctl -u oqto -f"
    fi
  fi
}

install_mmry_central_service() {
  # Central mmry-service runs as the oqto system user.
  # It loads the embeddings model once and serves it to all per-user mmry
  # instances via the external HTTP API on port 8091.
  log_info "Installing central mmry-service (embeddings server)..."

  local mmry_home="$OQTO_HOME"
  local mmry_config_dir="${mmry_home}/.config/mmry"
  local mmry_data_dir="${mmry_home}/.local/share/mmry"

  sudo mkdir -p "$mmry_config_dir" "$mmry_data_dir/stores"

  sudo tee "$mmry_config_dir/config.toml" >/dev/null <<EOF
[database]
path = "${mmry_data_dir}/memories.db"

[stores]
directory = "${mmry_data_dir}/stores"
default = "default"

[embeddings]
enabled = true
model = "Xenova/all-MiniLM-L6-v2"
backend = "fastembed"
dimension = 384
batch_size = 32

[service]
enabled = true
auto_start = true
idle_timeout_seconds = 0
preload_models = true

[external_api]
enable = true
host = "127.0.0.1"
port = 8091
require_api_key = false
EOF

  sudo chown -R oqto:oqto "$mmry_config_dir" "$mmry_data_dir"

  local service_file="/etc/systemd/system/mmry-central.service"
  sudo tee "$service_file" >/dev/null <<EOF
[Unit]
Description=Central mmry embeddings server
After=network.target

[Service]
Type=simple
User=oqto
Group=oqto
ExecStart=/usr/local/bin/mmry-service
Restart=always
RestartSec=5
Environment=HOME=${mmry_home}
Environment=RUST_LOG=mmry=info

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable mmry-central
  if sudo systemctl start mmry-central; then
    log_success "mmry-central service installed and started (port 8091)"
  else
    log_error "mmry-central failed to start. Check: sudo journalctl -xeu mmry-central.service"
    return 1
  fi
}

install_usermgr_service() {
  # oqto-usermgr runs as root and listens on a unix socket.
  # The oqto service (unprivileged) sends JSON requests over the socket
  # to create/delete Linux users, manage directories, etc.
  # This provides OS-level privilege separation.
  log_info "Installing oqto-usermgr service..."

  local service_file="/etc/systemd/system/oqto-usermgr.service"
  sudo tee "$service_file" >/dev/null <<EOF
[Unit]
Description=Oqto User Manager (privileged helper)
Before=oqto.service

[Service]
Type=simple
ExecStart=/usr/local/bin/oqto-usermgr
Restart=on-failure
RestartSec=3
RuntimeDirectory=oqto
RuntimeDirectoryMode=0775
RuntimeDirectoryPreserve=yes
ExecStartPost=/bin/chgrp oqto /run/oqto
ProtectSystem=strict
ReadWritePaths=/etc
ReadWritePaths=/home
ReadWritePaths=/run/oqto
ReadWritePaths=/var/lib/oqto
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable oqto-usermgr
  if sudo systemctl start oqto-usermgr; then
    log_success "oqto-usermgr service installed and started"
  else
    log_error "oqto-usermgr failed to start. Check: sudo journalctl -xeu oqto-usermgr.service"
    return 1
  fi
}

install_runner_socket_dirs() {
  # Ensure the shared runner socket base directory exists at boot.
  # Per-user subdirectories are created by oqto-usermgr at user creation time.
  # Per-user service files (oqto-runner, hstry, mmry) are also created by usermgr.
  log_info "Setting up runner socket directories..."

  local tmpfiles_conf="/etc/tmpfiles.d/oqto-runner.conf"

  sudo tee "$tmpfiles_conf" >/dev/null <<'EOF'
d /run/oqto 0775 root oqto -
d /run/oqto/runner-sockets 2770 root oqto -
EOF

  sudo systemd-tmpfiles --create "$tmpfiles_conf" >/dev/null 2>&1 || true

  # Remove any stale global service template (usermgr now handles per-user service files)
  if [[ -f /etc/systemd/user/oqto-runner.service ]]; then
    sudo rm -f /etc/systemd/user/oqto-runner.service
    log_info "Removed stale global oqto-runner.service template"
  fi

  log_success "Runner socket directories configured"
}

install_service_macos() {
  log_step "Installing launchd service"

  local plist_dir="$HOME/Library/LaunchAgents"
  local log_dir="$HOME/Library/Logs"
  mkdir -p "$plist_dir" "$log_dir"

  local plist_file="$plist_dir/ai.oqto.server.plist"

  # Determine serve flags
  local serve_flags=""
  if [[ "$SELECTED_BACKEND_MODE" == "local" ]]; then
    serve_flags="<string>--local-mode</string>"
  fi

  cat >"$plist_file" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>ai.oqto.server</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/oqto</string>
        <string>serve</string>
        $serve_flags
    </array>

    <key>EnvironmentVariables</key>
    <dict>
        <key>OQTO_CONFIG</key>
        <string>$OQTO_CONFIG_DIR/config.toml</string>
        <key>RUST_LOG</key>
        <string>$OQTO_LOG_LEVEL</string>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:$HOME/.bun/bin</string>
    </dict>

    <key>WorkingDirectory</key>
    <string>$HOME</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
        <key>Crashed</key>
        <true/>
    </dict>

    <key>ThrottleInterval</key>
    <integer>5</integer>

    <key>StandardOutPath</key>
    <string>$log_dir/oqto.stdout.log</string>

    <key>StandardErrorPath</key>
    <string>$log_dir/oqto.stderr.log</string>
</dict>
</plist>
EOF

  log_success "Launchd plist created: $plist_file"

  if confirm "Load and start the service now?"; then
    # Unload if already loaded
    launchctl unload "$plist_file" 2>/dev/null || true
    launchctl load "$plist_file"
    log_success "Service loaded and started"
    log_info "Check status with: launchctl list | grep oqto"
    log_info "View logs at: $log_dir/oqto.*.log"
  else
    log_info "To load manually:"
    log_info "  launchctl load $plist_file"
  fi
}

install_service() {
  if [[ "$OQTO_INSTALL_SERVICE" != "yes" ]]; then
    log_info "Skipping service installation (OQTO_INSTALL_SERVICE=no)"
    return
  fi

  case "$OS" in
  linux)
    install_service_linux
    ;;
  macos)
    install_service_macos
    ;;
  esac
}

